### ISSUE TITLE
#4 - exam

### ISSUE THREAD

**Issue by dunamisyoung** [fastcampus-hackerton-2020/GD-and-children#6]
- [x] 서버에서 참여코드에 할당된 문제 받아 로드/렌더링 기능
- [x] 총문제 갯수 확인 및 현재 푼 문제확인 기능
- [x] 풀지 않은 문제있으면  에러를 띄우는 기능
- [x] save 버튼누르면 경고창을통해 점수반환 or 다시풀기 기능

**Comment by dunamisyoung** [comment]
> * [ ]  서버에서 참여코드에 할당된 문제 받아 로드/렌더링 기능
> * [ ]  총문제 갯수 확인 및 현재 푼 문제확인 기능
> * [ ]  풀지 않은 문제있으면  에러를 띄우는 기능
> * [ ]  save 버튼누르면 input에 값을 answer에 추가 기능
> * [ ]  save 버튼누르면 경고창을통해 전송 or 비전송 기능

**Comment by hanseul-lee** [comment]
네 확인했습니다^^
